server:
  http2:
    enabled: true
  port: 8080
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

